const STATION_LIST = [
  {
    name: '12th St. Oakland City Center',
    shortName: '12th Street',
    abbreviation: '12TH',
    latitude: 37.803768,
    longitude: -122.271450,
    address: '1245 Broadway',
    city: 'Oakland',
    county: 'Alameda',
    state: 'CA',
    zipCode: '94612',
  },
  {
    name: '16th St. Mission',
    shortName: '16th Street',
    abbreviation: '16TH',
    latitude: 37.765062,
    longitude: -122.419694,
    address: '2000 Mission Street',
    city: 'San Francisco',
    county: 'San Francisco',
    state: 'CA',
    zipCode: '94110',
  },
  {
    name: '19th St. Oakland',
    shortName: '19th Street',
    abbreviation: '19TH',
    latitude: 37.808350,
    longitude: -122.268602,
    address: '1900 Broadway',
    city: 'Oakland',
    county: 'Alameda',
    state: 'CA',
    zipCode: '94612',
  },
  {
    name: '24th St. Mission',
    shortName: '24th Street',
    abbreviation: '24TH',
    latitude: 37.752470,
    longitude: -122.418143,
    address: '2800 Mission Street',
    city: 'San Francisco',
    county: 'San Francisco',
    state: 'CA',
    zipCode: '94110',
  },
  {
    name: 'Antioch',
    shortName: 'Antioch',
    abbreviation: 'ANTC',
    latitude: 37.995388,
    longitude: -121.780420,
    address: '1600 Slatten Ranch Road',
    city: 'Antioch',
    county: 'Contra Costa',
    state: 'CA',
    zipCode: '94509',
  },
  {
    name: 'Ashby',
    shortName: 'Ashby',
    abbreviation: 'ASHB',
    latitude: 37.852803,
    longitude: -122.270062,
    address: '3100 Adeline Street',
    city: 'Berkeley',
    county: 'Alameda',
    state: 'CA',
    zipCode: '94703',
  },
  {
    name: 'Balboa Park',
    shortName: 'Balboa Park',
    abbreviation: 'BALB',
    latitude: 37.721585,
    longitude: -122.447506,
    address: '401 Geneva Avenue',
    city: 'San Francisco',
    county: 'San Francisco',
    state: 'CA',
    zipCode: '94112',
  },
  {
    name: 'Bay Fair',
    shortName: 'Bay Fair',
    abbreviation: 'BAYF',
    latitude: 37.696924,
    longitude: -122.126514,
    address: '15242 Hesperian Blvd.',
    city: 'San Leandro',
    county: 'Alameda',
    state: 'CA',
    zipCode: '94578',
  },
  {
    name: 'Castro Valley',
    shortName: 'Castro Valley',
    abbreviation: 'CAST',
    latitude: 37.690746,
    longitude: -122.075602,
    address: '3301 Norbridge Dr.',
    city: 'Castro Valley',
    county: 'Alameda',
    state: 'CA',
    zipCode: '94546',
  },
  {
    name: 'Civic Center/UN Plaza',
    shortName: 'Civic Center',
    abbreviation: 'CIVC',
    latitude: 37.779732,
    longitude: -122.414123,
    address: '1150 Market Street',
    city: 'San Francisco',
    county: 'San Francisco',
    state: 'CA',
    zipCode: '94102',
  },
  {
    name: 'Coliseum',
    shortName: 'Coliseum',
    abbreviation: 'COLS',
    latitude: 37.753661,
    longitude: -122.196869,
    address: '7200 San Leandro St.',
    city: 'Oakland',
    county: 'Alameda',
    state: 'CA',
    zipCode: '94621',
  },
  {
    name: 'Colma',
    shortName: 'Colma',
    abbreviation: 'COLM',
    latitude: 37.684638,
    longitude: -122.466233,
    address: '365 D Street',
    city: 'Colma',
    county: 'San Mateo',
    state: 'CA',
    zipCode: '94014',
  },
  {
    name: 'Concord',
    shortName: 'Concord',
    abbreviation: 'CONC',
    latitude: 37.973737,
    longitude: -122.029095,
    address: '1451 Oakland Avenue',
    city: 'Concord',
    county: 'Contra Costa',
    state: 'CA',
    zipCode: '94520',
  },
  {
    name: 'Daly City',
    shortName: 'Daly City',
    abbreviation: 'DALY',
    latitude: 37.706121,
    longitude: -122.469081,
    address: '500 John Daly Blvd.',
    city: 'Daly City',
    county: 'San Mateo',
    state: 'CA',
    zipCode: '94014',
  },
  {
    name: 'Downtown Berkeley',
    shortName: 'Downtown Berkeley',
    abbreviation: 'DBRK',
    latitude: 37.870104,
    longitude: -122.268133,
    address: '2160 Shattuck Avenue',
    city: 'Berkeley',
    county: 'Alameda',
    state: 'CA',
    zipCode: '94704',
  },
  {
    name: 'Dublin/Pleasanton',
    shortName: 'Dublin/Pleasanton',
    abbreviation: 'DUBL',
    latitude: 37.701687,
    longitude: -121.899179,
    address: '5801 Owens Dr.',
    city: 'Pleasanton',
    county: 'Alameda',
    state: 'CA',
    zipCode: '94588',
  },
  {
    name: 'El Cerrito del Norte',
    shortName: 'El Cerrito del Norte',
    abbreviation: 'DELN',
    latitude: 37.925086,
    longitude: -122.316794,
    address: '6400 Cutting Blvd.',
    city: 'El Cerrito',
    county: 'Contra Costa',
    state: 'CA',
    zipCode: '94530',
  },
  {
    name: 'El Cerrito Plaza',
    shortName: 'El Cerrito Plaza',
    abbreviation: 'PLZA',
    latitude: 37.902632,
    longitude: -122.298904,
    address: '6699 Fairmount Avenue',
    city: 'El Cerrito',
    county: 'Contra Costa',
    state: 'CA',
    zipCode: '94530',
  },
  {
    name: 'Embarcadero',
    shortName: 'Embarcadero',
    abbreviation: 'EMBR',
    latitude: 37.792874,
    longitude: -122.397020,
    address: '298 Market Street',
    city: 'San Francisco',
    county: 'San Francisco',
    state: 'CA',
    zipCode: '94111',
  },
  {
    name: 'Fremont',
    shortName: 'Fremont',
    abbreviation: 'FRMT',
    latitude: 37.557465,
    longitude: -121.976608,
    address: '2000 BART Way',
    city: 'Fremont',
    county: 'Alameda',
    state: 'CA',
    zipCode: '94536',
  },
  {
    name: 'Fruitvale',
    shortName: 'Fruitvale',
    abbreviation: 'FTVL',
    latitude: 37.774836,
    longitude: -122.224175,
    address: '3401 East 12th Street',
    city: 'Oakland',
    county: 'Alameda',
    state: 'CA',
    zipCode: '94601',
  },
  {
    name: 'Glen Park',
    shortName: 'Glen Park',
    abbreviation: 'GLEN',
    latitude: 37.733064,
    longitude: -122.433817,
    address: '2901 Diamond Street',
    city: 'San Francisco',
    county: 'San Francisco',
    state: 'CA',
    zipCode: '94131',
  },
  {
    name: 'Hayward',
    shortName: 'Hayward',
    abbreviation: 'HAYW',
    latitude: 37.669723,
    longitude: -122.087018,
    address: '699 \'B\' Street',
    city: 'Hayward',
    county: 'Alameda',
    state: 'CA',
    zipCode: '94541',
  },
  {
    name: 'Lafayette',
    shortName: 'Lafayette',
    abbreviation: 'LAFY',
    latitude: 37.893176,
    longitude: -122.124630,
    address: '3601 Deer Hill Road',
    city: 'Lafayette',
    county: 'Contra Costa',
    state: 'CA',
    zipCode: '94549',
  },
  {
    name: 'Lake Merritt',
    shortName: 'Lake Merritt',
    abbreviation: 'LAKE',
    latitude: 37.797027,
    longitude: -122.265180,
    address: '800 Madison Street',
    city: 'Oakland',
    county: 'Alameda',
    state: 'CA',
    zipCode: '94607',
  },
  {
    name: 'MacArthur',
    shortName: 'MacArthur',
    abbreviation: 'MCAR',
    latitude: 37.829065,
    longitude: -122.267040,
    address: '555 40th Street',
    city: 'Oakland',
    county: 'Alameda',
    state: 'CA',
    zipCode: '94609',
  },
  {
    name: 'Millbrae',
    shortName: 'Millbrae',
    abbreviation: 'MLBR',
    latitude: 37.600271,
    longitude: -122.386702,
    address: '200 North Rollins Road',
    city: 'Millbrae',
    county: 'San Mateo',
    state: 'CA',
    zipCode: '94030',
  },
  {
    name: 'Montgomery St.',
    shortName: 'Montgomery',
    abbreviation: 'MONT',
    latitude: 37.789405,
    longitude: -122.401066,
    address: '598 Market Street',
    city: 'San Francisco',
    county: 'San Francisco',
    state: 'CA',
    zipCode: '94104',
  },
  {
    name: 'North Berkeley',
    shortName: 'North Berkeley',
    abbreviation: 'NBRK',
    latitude: 37.873967,
    longitude: -122.283440,
    address: '1750 Sacramento Street',
    city: 'Berkeley',
    county: 'Alameda',
    state: 'CA',
    zipCode: '94702',
  },
  {
    name: 'North Concord/Martinez',
    shortName: 'North Concord',
    abbreviation: 'NCON',
    latitude: 38.003193,
    longitude: -122.024653,
    address: '3700 Port Chicago Highway',
    city: 'Concord',
    county: 'Contra Costa',
    state: 'CA',
    zipCode: '94520',
  },
  {
    name: 'Oakland International Airport',
    shortName: 'Oakland Airport',
    abbreviation: 'OAKL',
    latitude: 37.713238,
    longitude: -122.212191,
    address: '4 Airport Drive',
    city: 'Oakland',
    county: 'Alameda',
    state: 'CA',
    zipCode: '94621',
  },
  {
    name: 'Orinda',
    shortName: 'Orinda',
    abbreviation: 'ORIN',
    latitude: 37.878361,
    longitude: -122.183791,
    address: '11 Camino Pablo',
    city: 'Orinda',
    county: 'Contra Costa',
    state: 'CA',
    zipCode: '94563',
  },
  {
    name: 'Pittsburg/Bay Point',
    shortName: 'Pittsburg/Bay Point',
    abbreviation: 'PITT',
    latitude: 38.018914,
    longitude: -121.945154,
    address: '1700 West Leland Road',
    city: 'Pittsburg',
    county: 'Contra Costa',
    state: 'CA',
    zipCode: '94565',
  },
  {
    name: 'Pittsburg Center',
    shortName: 'Pittsburg Center',
    abbreviation: 'PCTR',
    latitude: 38.016941,
    longitude: -121.889457,
    address: '2099 Railroad Avenue',
    city: 'Pittsburg',
    county: 'Contra Costa',
    state: 'CA',
    zipCode: '94565',
  },
  {
    name: 'Pleasant Hill/Contra Costa Centre',
    shortName: 'Pleasant Hill',
    abbreviation: 'PHIL',
    latitude: 37.928468,
    longitude: -122.056012,
    address: '1365 Treat Blvd.',
    city: 'Walnut Creek',
    county: 'Contra Costa',
    state: 'CA',
    zipCode: '94597',
  },
  {
    name: 'Powell St.',
    shortName: 'Powell',
    abbreviation: 'POWL',
    latitude: 37.784471,
    longitude: -122.407974,
    address: '899 Market Street',
    city: 'San Francisco',
    county: 'San Francisco',
    state: 'CA',
    zipCode: '94102',
  },
  {
    name: 'Richmond',
    shortName: 'Richmond',
    abbreviation: 'RICH',
    latitude: 37.936853,
    longitude: -122.353099,
    address: '1700 Nevin Avenue',
    city: 'Richmond',
    county: 'Contra Costa',
    state: 'CA',
    zipCode: '94801',
  },
  {
    name: 'Rockridge',
    shortName: 'Rockridge',
    abbreviation: 'ROCK',
    latitude: 37.844702,
    longitude: -122.251371,
    address: '5660 College Avenue',
    city: 'Oakland',
    county: 'Alameda',
    state: 'CA',
    zipCode: '94618',
  },
  {
    name: 'San Bruno',
    shortName: 'San Bruno',
    abbreviation: 'SBRN',
    latitude: 37.637761,
    longitude: -122.416287,
    address: '1151 Huntington Avenue',
    city: 'San Bruno',
    county: 'San Mateo',
    state: 'CA',
    zipCode: '94066',
  },
  {
    name: 'San Francisco International Airport',
    shortName: 'SFO',
    abbreviation: 'SFIA',
    latitude: 37.615966,
    longitude: -122.392409,
    address: 'International Terminal, Level 3',
    city: 'San Francisco Int\'l Airport',
    county: 'San Mateo',
    state: 'CA',
    zipCode: '94128',
  },
  {
    name: 'San Leandro',
    shortName: 'San Leandro',
    abbreviation: 'SANL',
    latitude: 37.721947,
    longitude: -122.160844,
    address: '1401 San Leandro Blvd.',
    city: 'San Leandro',
    county: 'Alameda',
    state: 'CA',
    zipCode: '94577',
  },
  {
    name: 'South Hayward',
    shortName: 'South Hayward',
    abbreviation: 'SHAY',
    latitude: 37.634375,
    longitude: -122.057189,
    address: '28601 Dixon Street',
    city: 'Hayward',
    county: 'Alameda',
    state: 'CA',
    zipCode: '94544',
  },
  {
    name: 'South San Francisco',
    shortName: 'South San Francisco',
    abbreviation: 'SSAN',
    latitude: 37.664245,
    longitude: -122.443960,
    address: '1333 Mission Road',
    city: 'South San Francisco',
    county: 'San Mateo',
    state: 'CA',
    zipCode: '94080',
  },
  {
    name: 'Union City',
    shortName: 'Union City',
    abbreviation: 'UCTY',
    latitude: 37.590630,
    longitude: -122.017388,
    address: '10 Union Square',
    city: 'Union City',
    county: 'Alameda',
    state: 'CA',
    zipCode: '94587',
  },
  {
    name: 'Walnut Creek',
    shortName: 'Walnut Creek',
    abbreviation: 'WCRK',
    latitude: 37.905522,
    longitude: -122.067527,
    address: '200 Ygnacio Valley Road',
    city: 'Walnut Creek',
    county: 'Contra Costa',
    state: 'CA',
    zipCode: '94596',
  },
  {
    name: 'Warm Springs/South Fremont',
    shortName: 'Warm Springs',
    abbreviation: 'WARM',
    latitude: 37.502171,
    longitude: -121.939313,
    address: '45193 Warm Springs Blvd',
    city: 'Fremont',
    county: 'Alameda',
    state: 'CA',
    zipCode: '94539',
  },
  {
    name: 'West Dublin/Pleasanton',
    shortName: 'West Dublin',
    abbreviation: 'WDUB',
    latitude: 37.699756,
    longitude: -121.928240,
    address: '6501 Golden Gate Drive',
    city: 'Dublin',
    county: 'Alameda',
    state: 'CA',
    zipCode: '94568',
  },
  {
    name: 'West Oakland',
    shortName: 'West Oakland',
    abbreviation: 'WOAK',
    latitude: 37.804872,
    longitude: -122.295140,
    address: '1451 7th Street',
    city: 'Oakland',
    county: 'Alameda',
    state: 'CA',
    zipCode: '94607',
  },
];

export default STATION_LIST;
