const ActionTypes = {
  GET_ADVISORIES_START: 'GET_ADVISORIES_START',
  GET_ADVISORIES_SUCCESS: 'GET_ADVISORIES_SUCCESS',
  GET_ADVISORIES_FAILURE: 'GET_ADVISORIES_FAILURE',

  UPDATE_STATION_LINK: 'UPDATE_STATION_LINK',
};

export default ActionTypes;
