export default {
  "abbreviation": "POWL",
  "arrivals": {
    "northBound": {
      "list": [
        {
          "abbreviation": "DUBL",
          "arrivalID": "DUBL01_4348800",
          "canBikesRide": true,
          "color": "BLUE",
          "delay": 162,
          "direction": "North",
          "hexColor": "#0099cc",
          "isLimited": false,
          "length": 8,
          "minutes": "3",
          "name": "Dublin/Pleasanton",
          "platform": "2"
        },
        {
          "abbreviation": "RICH",
          "arrivalID": "RICH01_d4af3c7",
          "canBikesRide": true,
          "color": "RED",
          "delay": 0,
          "direction": "North",
          "hexColor": "#ff0000",
          "isLimited": false,
          "length": 9,
          "minutes": "10",
          "name": "Richmond",
          "platform": "2"
        },
        {
          "abbreviation": "ANTC",
          "arrivalID": "ANTC01_137d99d",
          "canBikesRide": true,
          "color": "YELLOW",
          "delay": 0,
          "direction": "North",
          "hexColor": "#ffff33",
          "isLimited": false,
          "length": 9,
          "minutes": "13",
          "name": "Antioch",
          "platform": "2"
        },
        {
          "abbreviation": "DUBL",
          "arrivalID": "DUBL02_4348800",
          "canBikesRide": true,
          "color": "BLUE",
          "delay": 0,
          "direction": "North",
          "hexColor": "#0099cc",
          "isLimited": false,
          "length": 9,
          "minutes": "21",
          "name": "Dublin/Pleasanton",
          "platform": "2"
        },
        {
          "abbreviation": "RICH",
          "arrivalID": "RICH02_d4af3c7",
          "canBikesRide": true,
          "color": "RED",
          "delay": 0,
          "direction": "North",
          "hexColor": "#ff0000",
          "isLimited": false,
          "length": 9,
          "minutes": "30",
          "name": "Richmond",
          "platform": "2"
        },
        {
          "abbreviation": "ANTC",
          "arrivalID": "ANTC02_137d99d",
          "canBikesRide": true,
          "color": "YELLOW",
          "delay": 0,
          "direction": "North",
          "hexColor": "#ffff33",
          "isLimited": false,
          "length": 10,
          "minutes": "33",
          "name": "Antioch",
          "platform": "2"
        },
        {
          "abbreviation": "DUBL",
          "arrivalID": "DUBL03_4348800",
          "canBikesRide": true,
          "color": "BLUE",
          "delay": 0,
          "direction": "North",
          "hexColor": "#0099cc",
          "isLimited": false,
          "length": 9,
          "minutes": "41",
          "name": "Dublin/Pleasanton",
          "platform": "2"
        },
        {
          "abbreviation": "RICH",
          "arrivalID": "RICH03_d4af3c7",
          "canBikesRide": true,
          "color": "RED",
          "delay": 0,
          "direction": "North",
          "hexColor": "#ff0000",
          "isLimited": false,
          "length": 9,
          "minutes": "50",
          "name": "Richmond",
          "platform": "2"
        },
        {
          "abbreviation": "ANTC",
          "arrivalID": "ANTC03_137d99d",
          "canBikesRide": true,
          "color": "YELLOW",
          "delay": 0,
          "direction": "North",
          "hexColor": "#ffff33",
          "isLimited": false,
          "length": 10,
          "minutes": "53",
          "name": "Antioch",
          "platform": "2"
        }
      ],
      "name": "North",
      "platforms": new Set(["2"])
    },
    "southBound": {
      "list": [
        {
          "abbreviation": "DALY",
          "arrivalID": "DALY01_c1ceb36",
          "canBikesRide": true,
          "color": "BLUE",
          "delay": 0,
          "direction": "South",
          "hexColor": "#0099cc",
          "isLimited": false,
          "length": 9,
          "minutes": "4",
          "name": "Daly City",
          "platform": "1"
        },
        {
          "abbreviation": "MLBR",
          "arrivalID": "MLBR01_a1a19e1",
          "canBikesRide": true,
          "color": "YELLOW",
          "delay": 0,
          "direction": "South",
          "hexColor": "#ffff33",
          "isLimited": false,
          "length": 10,
          "minutes": "11",
          "name": "SFO/Millbrae",
          "platform": "1"
        },
        {
          "abbreviation": "DALY",
          "arrivalID": "DALY02_c1ceb36",
          "canBikesRide": true,
          "color": "BLUE",
          "delay": 0,
          "direction": "South",
          "hexColor": "#0099cc",
          "isLimited": false,
          "length": 10,
          "minutes": "25",
          "name": "Daly City",
          "platform": "1"
        },
        {
          "abbreviation": "MLBR",
          "arrivalID": "MLBR02_a1a19e1",
          "canBikesRide": true,
          "color": "YELLOW",
          "delay": 0,
          "direction": "South",
          "hexColor": "#ffff33",
          "isLimited": false,
          "length": 10,
          "minutes": "31",
          "name": "SFO/Millbrae",
          "platform": "1"
        },
        {
          "abbreviation": "DALY",
          "arrivalID": "DALY03_c1ceb36",
          "canBikesRide": true,
          "color": "BLUE",
          "delay": 0,
          "direction": "South",
          "hexColor": "#0099cc",
          "isLimited": false,
          "length": 10,
          "minutes": "45",
          "name": "Daly City",
          "platform": "1"
        },
        {
          "abbreviation": "MLBR",
          "arrivalID": "MLBR03_a1a19e1",
          "canBikesRide": true,
          "color": "YELLOW",
          "delay": 0,
          "direction": "South",
          "hexColor": "#ffff33",
          "isLimited": false,
          "length": 10,
          "minutes": "51",
          "name": "SFO/Millbrae",
          "platform": "1"
        }
      ],
      "name": "South",
      "platforms": new Set(["1"])
    }
  },
  "date": "11/20/2018",
  "name": "Powell St.",
  "time": "08:23:16 PM PST"
}
