export default {
  "abbreviation": "POWL",
  "list": [
    {
      "abbreviation": "ANTC",
      "departureID": "ANTC01_137d99d",
      "canBikesRide": true,
      "color": "YELLOW",
      "delay": 0,
      "direction": "North",
      "hexColor": "#ffff33",
      "isLimited": false,
      "length": 9,
      "minutes": 13,
      "name": "Antioch",
      "platform": "2"
    },
    {
      "abbreviation": "ANTC",
      "departureID": "ANTC02_137d99d",
      "canBikesRide": true,
      "color": "YELLOW",
      "delay": 0,
      "direction": "North",
      "hexColor": "#ffff33",
      "isLimited": false,
      "length": 10,
      "minutes": 33,
      "name": "Antioch",
      "platform": "2"
    },
    {
      "abbreviation": "ANTC",
      "departureID": "ANTC03_137d99d",
      "canBikesRide": true,
      "color": "YELLOW",
      "delay": 0,
      "direction": "North",
      "hexColor": "#ffff33",
      "isLimited": false,
      "length": 10,
      "minutes": 53,
      "name": "Antioch",
      "platform": "2"
    },

    {
      "abbreviation": "DALY",
      "departureID": "DALY01_c1ceb36",
      "canBikesRide": true,
      "color": "BLUE",
      "delay": 0,
      "direction": "South",
      "hexColor": "#0099cc",
      "isLimited": false,
      "length": 9,
      "minutes": 4,
      "name": "Daly City",
      "platform": "1"
    },
    {
      "abbreviation": "DALY",
      "departureID": "DALY02_c1ceb36",
      "canBikesRide": true,
      "color": "BLUE",
      "delay": 0,
      "direction": "South",
      "hexColor": "#0099cc",
      "isLimited": false,
      "length": 10,
      "minutes": 25,
      "name": "Daly City",
      "platform": "1"
    },
    {
      "abbreviation": "DALY",
      "departureID": "DALY03_c1ceb36",
      "canBikesRide": true,
      "color": "BLUE",
      "delay": 0,
      "direction": "South",
      "hexColor": "#0099cc",
      "isLimited": false,
      "length": 10,
      "minutes": 45,
      "name": "Daly City",
      "platform": "1"
    },
    {
      "abbreviation": "DUBL",
      "departureID": "DUBL01_4348800",
      "canBikesRide": true,
      "color": "BLUE",
      "delay": 162,
      "direction": "North",
      "hexColor": "#0099cc",
      "isLimited": false,
      "length": 8,
      "minutes": 0,
      "name": "Dublin/Pleasanton",
      "platform": "2"
    },
    {
      "abbreviation": "DUBL",
      "departureID": "DUBL02_4348800",
      "canBikesRide": true,
      "color": "BLUE",
      "delay": 0,
      "direction": "North",
      "hexColor": "#0099cc",
      "isLimited": false,
      "length": 9,
      "minutes": 21,
      "name": "Dublin/Pleasanton",
      "platform": "2"
    },
    {
      "abbreviation": "DUBL",
      "departureID": "DUBL03_4348800",
      "canBikesRide": true,
      "color": "BLUE",
      "delay": 0,
      "direction": "North",
      "hexColor": "#0099cc",
      "isLimited": false,
      "length": 9,
      "minutes": 41,
      "name": "Dublin/Pleasanton",
      "platform": "2"
    },
    {
      "abbreviation": "RICH",
      "departureID": "RICH01_d4af3c7",
      "canBikesRide": true,
      "color": "RED",
      "delay": 0,
      "direction": "North",
      "hexColor": "#ff0000",
      "isLimited": false,
      "length": 9,
      "minutes": 10,
      "name": "Richmond",
      "platform": "2"
    },
    {
      "abbreviation": "RICH",
      "departureID": "RICH02_d4af3c7",
      "canBikesRide": true,
      "color": "RED",
      "delay": 0,
      "direction": "North",
      "hexColor": "#ff0000",
      "isLimited": false,
      "length": 9,
      "minutes": 30,
      "name": "Richmond",
      "platform": "2"
    },
    {
      "abbreviation": "RICH",
      "departureID": "RICH03_d4af3c7",
      "canBikesRide": true,
      "color": "RED",
      "delay": 0,
      "direction": "North",
      "hexColor": "#ff0000",
      "isLimited": false,
      "length": 9,
      "minutes": 50,
      "name": "Richmond",
      "platform": "2"
    },
    {
      "abbreviation": "MLBR",
      "departureID": "MLBR01_a1a19e1",
      "canBikesRide": true,
      "color": "YELLOW",
      "delay": 0,
      "direction": "South",
      "hexColor": "#ffff33",
      "isLimited": false,
      "length": 10,
      "minutes": 11,
      "name": "SFO/Millbrae",
      "platform": "1"
    },
    {
      "abbreviation": "MLBR",
      "departureID": "MLBR02_a1a19e1",
      "canBikesRide": true,
      "color": "YELLOW",
      "delay": 0,
      "direction": "South",
      "hexColor": "#ffff33",
      "isLimited": false,
      "length": 10,
      "minutes": 31,
      "name": "SFO/Millbrae",
      "platform": "1"
    },
    {
      "abbreviation": "MLBR",
      "departureID": "MLBR03_a1a19e1",
      "canBikesRide": true,
      "color": "YELLOW",
      "delay": 0,
      "direction": "South",
      "hexColor": "#ffff33",
      "isLimited": false,
      "length": 10,
      "minutes": 51,
      "name": "SFO/Millbrae",
      "platform": "1"
    },
  ],
  "date": "11/20/2018",
  "name": "Powell St.",
  "time": "08:23:16 PM PST"
}
