module.exports = {
  // COLORS
  COLOR_BRAND_PRIMARY: '#0095d6',

  COLOR_DEFAULT_WHITE: 'white',
  COLOR_TRANSPARENT_WHITE: 'rgba(255,255,255,.95)',
  COLOR_SEMI_TRANSPARENT_WHITE: 'rgba(255,255,255,.5)',

  COLOR_DEFAULT_WHITESMOKE: 'whitesmoke',

  COLOR_DEFAULT_LIGHTGRAY: 'lightgray',

  COLOR_DEFAULT_IRON: '#5e5e5e',

  COLOR_DEFAULT_LEAD: '#2f2f2f',

  COLOR_DEFAULT_BLACK: 'black',
  COLOR_TRANSPARENT_BLACK: 'rgba(0,0,0,.95)',
  COLOR_SEMI_TRANSPARENT_BLACK: 'rgba(0,0,0,.5)',

  COLOR_WARNING_RED: '#e53935',

  COLOR_DEFAULT_BLUE: '#001fff',
  COLOR_DEFAULT_LIGHTBLUE: '#008dff',

  // ROUTE COLORS
  COLOR_ROUTE_YELLOW: '#ffff33',
  COLOR_ROUTE_BLUE: '#0099cc',
  COLOR_ROUTE_GREEN: '#339933',
  COLOR_ROUTE_ORANGE: '#ff9933',
  COLOR_ROUTE_RED: '#ff0000',
  COLOR_ROUTE_WHITE: '#ffffff',
  COLOR_ROUTE_TAN: '#d5cfa3',

  // PADDINGS
  PADDING_SMALL: '.5rem',
  PADDING_MEDIUM: '.75rem',
  PADDING_LARGE: '1rem',

  // BREAKPOINTS
  BREAKPOINT_SMALL: '600px',
  BREAKPOINT_MEDIUM: '960px',
  BREAKPOINT_LARGE: '1280px',
  BREAKPOINT_EXTRA_LARGE: '1920px',
};
