module.exports = {
  COLOR_ROUTE_YELLOW: '#ffff33',
  COLOR_ROUTE_BLUE: '#0099cc',
  COLOR_ROUTE_GREEN: '#339933',
  COLOR_ROUTE_ORANGE: '#ff9933',
  COLOR_ROUTE_RED: '#ff0000',
  COLOR_ROUTE_WHITE: '#ffffff',
  COLOR_ROUTE_TAN: '#d5cfa3',

  COLOR_DEFAULT_WHITE: 'white',
  COLOR_TRANSPARENT_WHITE: 'rgba(255,255,255,.95)',
  COLOR_SEMI_TRANSPARENT_WHITE: 'rgba(255,255,255,.5)',

  COLOR_DEFAULT_WHITESMOKE: 'whitesmoke',

  COLOR_DEFAULT_LIGHTGRAY: 'lightgray',

  COLOR_DEFAULT_IRON: '#5E5E5E',

  COLOR_DEFAULT_LEAD: '#1e1e1e',

  COLOR_DEFAULT_BLACK: 'black',
  COLOR_TRANSPARENT_BLACK: 'rgba(0,0,0,.95)',
  COLOR_SEMI_TRANSPARENT_BLACK: 'rgba(0,0,0,.5)',

  COLOR_WARNING_RED: '#E53935',
};
